name: native_app
description: >
  A command-line application to demonstrate compiling to native code using
  dart2native.

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: any
  build_cli_annotations: ^1.0.0
  github: any
  intl: any

dev_dependencies:
  build_cli: ^1.0.0
  build_runner: ^1.0.0
  pedantic: ^1.8.0
  test: ^1.6.0
dependency_overrides:
  github:
    path: /Users/ryjohn/code/github/johnpryan/github.dart
